### ISSUE TITLE
Build fails because of wrong image in App-Manifest

### ISSUE THREAD

**Issue by SteffoSpieler** [AestheticalZ/Bluechirp#44]
**Describe the bug:**
When I try to build the application with Visual Studio, I get at the end a table with 2 errors (and 9 warnings).

**To reproduce:**
1. Build the app.
2. Wait until build is finished.
3. See table with errors.

**Expected behavior:**
Don't have errors and get the app exported somewhere. 

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/41108856/236625463-8ddf8d06-f5cd-450d-aaf4-695f67f89217.png)

sorry that it's german, but the errors say the following:

> The app manifest refers to the "Square logo 150x 150-image 100.png", which does not have valid dimensions. It must be 150x 150
pixels.
> The app manifest points to the image that has no candidate in the main app package.

**System (please complete the following information):**
 - Windows: Windows 11 Version 22H2 Build 22621.1635
 - App Version: (latest commit in master branch)

**Comment by AestheticalZ** [comment]
Can't reproduce, although it seems the issue is that the image is 256x256. Attempting to fix.

**Comment by AestheticalZ** [comment]
I've pushed a fix attempt, can you pull and try to rebuild?

**Comment by SteffoSpieler** [comment]
okay, I think I got it. Building by clicking the green "play button" with the text "local computer" works. But when I try to build it by `rightclick > publish > create app package..` and then `sideload` and stuff, I get the error.

Though now I have only 1 error. `The app manifest refers to the image "Assets\Icons\Tiles\MedTile.png" which has no candidate in the main app package.`

I try to build in Release, and not Debug.

If you need more details, just ask me ^^

**Comment by AestheticalZ** [comment]
I have pushed another fix that allowed me to publish on my machine. Can you try it?

**Comment by SteffoSpieler** [comment]
yes, works also for me now! Thank you!
